### PR TITLE
Add pkg-config install to cmake build.

### PR DESCRIPTION
**Pull request by Crystalix007**
Added the required steps in the CMake build to populate the pkg-config template and install it into the pkg-config directory.

### CODE REVIEW

**Comment by mcsauder** [comment]
That's awesome! This works on my Ubuntu 20.04 machine and a fresh clone of the repo.  This looks good to me. 

@crayzeewulf , you have a better eye for this than I do, but from my side it looks good.

Thanks @Crystalix007 !

**Comment by crayzeewulf** [comment]
Awesome! I will have the opportunity to test it out tomorrow evening. I will let you know how it goes.

**Comment by crayzeewulf** [comment]
I completely forgot that I had done this in [cmake_pkg_config_integration](https://github.com/crayzeewulf/libserial/tree/cmake_pkg_config_integration) branch back in April. See [this](https://github.com/crayzeewulf/libserial/commit/7f7989018492304d5b87ba726e82d222d48fe921). I should have merged it.

**Comment by crayzeewulf** [comment]
I do like @Crystalix007's solution better because it works for both CMake and autotools.

**Comment by crayzeewulf** [comment]
Thanks, @Crystalix007. I will abandon my branch now that your solution has been merged.

**Comment by Crystalix007** [comment]
I completely forgot to check actually. I'll make sure to check that sort of thing before doing my next PR. Thanks.

**Pull request merged**
