### PR TITLE
Added try/catch cases for catching ReadTimeout exceptions to examples

### PR DESCRIPTION
**Pull request by mcsauder**
This PR just adds try/catch statements to the example code.

Let me know if you have any questions!

-Mark

### CODE REVIEW

**Comment by wade-fs** [comment]
No.
In the SerialPort::Read() implementation code....
must be do { .. } while(); not the original while () { ... }
Please look at my patch.

**Comment by mcsauder** [comment]
Hi @wade-fs ,

Could you help me localize this issue between the master branch and the c++14 branch?  Could you tell me if the problem exists in both the master and the c++14 branches?  I'm not quite understanding how changing the while() loop to a do(){...} while() loop is fixing the issue.

Thank you for helping me localize and understand what you are seeing.

-Mark

**Comment by mcsauder** [comment]
Hi @wade-fs ,

Also, there is a known issue with the master branch in threaded applications.  The master branch will not function as expected in a threaded application.  If you are using the master branch in a threaded application could you try the c++14 branch and let us know if that resolves the issue?  Thank you for your work on this!

-Mark

**Comment by crayzeewulf** [comment]
@wade-fs I believe that the implemented behavior is intentional and matches the documentation. As the documentation says:

> If numberOfBytes is zero, then this method will keep reading data till no more data is available at the serial port. 

The intention is to return all *currently available* data when `numberOfBytes` is set to 0. If no data is  available then it should return immediately and `dataBuffer` should be empty. 

Hope this makes sense. If not, please give us an example of how you are intending to use this method and what you expect it to do. Maybe there is another way to achieve the affect you want.

**Comment by wade-fs** [comment]
Just for Timeout issue for c++14 branch:
Please apply the patch.
And, I am not using multi-threading....so...

[Patch-SerialPort.txt](https://github.com/crayzeewulf/libserial/files/1520679/Patch-SerialPort.txt)

**Comment by crayzeewulf** [comment]
@wade-fs Please see [this](https://github.com/crayzeewulf/libserial/issues/93#issuecomment-348417396) comment.

**Comment by wade-fs** [comment]
I don't think so.


*If numberOfBytes is zero, then this method will keep reading data till no
more data is available at the serial port.*

Keep reading data : It must wait for data coming,
and then....read till no more data is available...


Best Regards
--
自由的精靈, 狂想的空間
Free Spirit, Fantasy Space

**Comment by crayzeewulf** [comment]
How about we move/continue the discussion to #93 where you posted the patch so all comments stay in once place. Sound good?

**Comment by mcsauder** [comment]
Perfect!  And thanks for helping us put down breadcrumbs for future readers!

Thanks again!

-Mark

**Pull request merged**
